package com.gestorDocumental.controller;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;

import javax.validation.Valid;
import javax.xml.bind.DatatypeConverter;

import org.apache.tomcat.util.http.fileupload.IOUtils;
import org.aspectj.bridge.Message;
import org.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.xhtmlrenderer.pdf.ITextRenderer;

import com.gestorDocumental.entity.DocumentoDigital;
import com.gestorDocumental.helper.SQLHelper;
import com.gestorDocumental.helper.FTPHelper;
import com.gestorDocumental.model.MCliente;
import com.gestorDocumental.model.MDocumentoDigital;
import com.gestorDocumental.model.MProceso;
import com.gestorDocumental.service.DocumentoDigitalService;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.pdf.PdfWriter;

@RestController
@RequestMapping("/api")
@CrossOrigin(origins = "*", methods = { RequestMethod.GET, RequestMethod.POST })
public class API {

	static final Logger LOG = LoggerFactory.getLogger(API.class);
	@Autowired
	private SQLHelper sqlHelper;
	@Autowired
	private FTPHelper ftpHelper;
	@Autowired
	@Qualifier("DigitalService")
	private DocumentoDigitalService docDigiService;

	@RequestMapping(value = "/guardarDocumento", method = RequestMethod.POST)
	public String guardarDocumento(@Valid @RequestBody String body) throws IOException {
		String ubicacion = null;
		try {
			JSONObject object = new JSONObject(body);
			String documentoDescripcion = object.getString("documentoTipo");
			ubicacion = sqlHelper.guardarDocumento(documentoDescripcion, 1, 2);
			return (ubicacion);
		} catch (Exception e) {
			e.printStackTrace();
			LOG.error("Error: " + e.getMessage());
			System.out.println(body);
		} finally {
		}
		return (ubicacion);
	}

	@RequestMapping(value = "/obtenerSubproceso", method = RequestMethod.POST)
	public List<String> obtenerSubproceso(@Valid @RequestBody String body) throws IOException {
		List<String> subprocesos = new ArrayList<String>();
		// String legajo = "pablo";
		try {
			JSONObject object = new JSONObject(body);
			String proceso = object.getString("procesoTipo");
			subprocesos = sqlHelper.obtenerSubproceso(proceso);
			return (subprocesos);
		} catch (Exception e) {
			e.printStackTrace();
			LOG.error("Error: " + e.getMessage());
			System.out.println(body);
		} finally {
		}
		return (subprocesos);
	}

	@RequestMapping(value = "/obtenerProceso", method = RequestMethod.POST)
	public List<MProceso> obtenerProceso() throws IOException {
		List<MProceso> procesos = new ArrayList<>();
		try {
			procesos = docDigiService.obtenerProcesos();
			return (procesos);
		} catch (Exception e) {
			e.printStackTrace();
			LOG.error("Error: " + e.getMessage());
		} finally {
		}
		return (procesos);
	}

	@RequestMapping(value = "/obtenerTiposDocumentosDeSubproceso", method = RequestMethod.POST)
	public List<String> obtenerTiposDocumentosDeSubproceso(@Valid @RequestBody String body) throws IOException {
		List<String> tiposDocumentales = new ArrayList<String>();
		// String legajo = "pablo";
		try {
			JSONObject object = new JSONObject(body);
			String proceso = object.getString("proceso");
			String subproceso = object.getString("subproceso");
			tiposDocumentales = sqlHelper.obtenerTiposDocumentosDeSubproceso(proceso, subproceso);
			return (tiposDocumentales);
		} catch (Exception e) {
			e.printStackTrace();
			LOG.error("Error: " + e.getMessage());
			System.out.println(body);
		} finally {
		}
		return (tiposDocumentales);
	}

	@RequestMapping(value = "/obtenerDocumentos", method = RequestMethod.POST)
	public List<MDocumentoDigital> obtenerDocumentos(@Valid @RequestBody String body) throws IOException {
		List<MDocumentoDigital> tiposDocumentales = new ArrayList<>();
		try {
			JSONObject object = new JSONObject(body);
			String proceso = object.getString("proceso");
			String subproceso = object.getString("subproceso");
			String operacion = object.getString("operacion");
			System.out.println("La operacion es: " + operacion);
			if (operacion.isEmpty()) {
				tiposDocumentales = docDigiService.obtenerPorProcesoSubProceso(proceso, subproceso);
				System.out.println("Busqueda solo por proceso y subproceso");
			} else {
				System.out.println("Busqueda solo por proceso, subproceso y operacion");
				tiposDocumentales = docDigiService.obtenerPorProcesoSubProcesoYOperacion(proceso, subproceso,
						operacion);
			}
			return (tiposDocumentales);
		} catch (Exception e) {
			e.printStackTrace();
			LOG.error("Error: " + e.getMessage());
			System.out.println(body);
		} finally {
		}
		return (tiposDocumentales);
	}

	@RequestMapping(value = "/obtenerDocumentosPorCliente", method = RequestMethod.POST)
	public List<MDocumentoDigital> obtenerDocumentosPorCliente(@Valid @RequestBody String body) throws IOException {
		List<MDocumentoDigital> documentos = new ArrayList<>();
		try {
			JSONObject object = new JSONObject(body);
			String cliente = object.getString("cliente");
			documentos = docDigiService.obtenerPorCliente(cliente);
			return (documentos);
		} catch (Exception e) {
			e.printStackTrace();
			LOG.error("Error: " + e.getMessage());
			System.out.println(body);
		} finally {
		}
		return (documentos);
	}

	@RequestMapping(value = "/obtenerClientePorNumero", method = RequestMethod.POST)
	public MCliente obtenerClientePorNumero(@Valid @RequestBody String body) throws IOException {
		MCliente cliente = null;
		try {
			JSONObject object = new JSONObject(body);
			Integer nroCliente = object.getInt("numeroCliente");
			cliente = docDigiService.obtenerPorNumero(nroCliente);
			return (cliente);
		} catch (Exception e) {
			e.printStackTrace();
			LOG.error("Error: " + e.getMessage());
			System.out.println(body);
		} finally {
		}
		return (cliente);
	}

	@RequestMapping(value = "/guardarDigital", method = RequestMethod.POST)
	public long guardarDigital(@Valid @RequestBody String body) throws IOException {
		DocumentoDigital documento = null;
		try {
			JSONObject object = new JSONObject(body);
			Integer solicitud = object.getInt("solicitud");
			String proceso = object.getString("proceso");
			String subProceso = object.getString("subProceso");
			String operacion = object.getString("operacion");
			String tipoDocumento = object.getString("tipoDocumento");
			String razonSocial = object.getString("razonSocial");

			documento = new DocumentoDigital(proceso, subProceso, operacion, tipoDocumento, razonSocial, "pablo",null);
			documento.setId(solicitud);
			documento.setBase64(docDigiService.obtenerPorIdDeDocumento(solicitud).getBase64());
			docDigiService.actualizarDocumentoDigital(documento);
			return (1);
		} catch (Exception e) {
			e.printStackTrace();
			LOG.error("Error: " + e.getMessage());
			System.out.println(body);
		} finally {
		}
		return (0);
	}

		@RequestMapping(value = "/enviarPdf", method = RequestMethod.POST)
		public long guardarPDF(InputStream is) throws IOException, InterruptedException, DocumentException {
			
			DocumentoDigital documento = new DocumentoDigital();
			long id = docDigiService.crearDocumentoDigital(documento);

			ByteArrayOutputStream buffer = new ByteArrayOutputStream();
			
			int nRead;
			byte[] data = new byte[16384];
			
			while ((nRead = is.read(data, 0, data.length)) != -1) {
				  buffer.write(data, 0, nRead);
				}
			
			buffer.toByteArray();
			
			String pdf = Base64.getEncoder().encodeToString(buffer.toByteArray());
			documento.setBase64(pdf);
			docDigiService.actualizarDocumentoDigital(documento);
			System.out.println("se guardo el base 64 del documento"); 
			
			FileOutputStream outStream = null;
			
			
			try {
				//String filePath = "src/main/resources/";
				//String newFileName = "doc_"+ id + ".pdf";
				//outStream = new FileOutputStream(filePath + newFileName);
			
				//byte[] decoded;
				//decoded = DatatypeConverter.parseBase64Binary(pdf);
				//outStream.write(decoded);
				//outStream.flush();
				//outStream.close();

			}catch(Exception e) {
				
			}finally {
	           //Thread.sleep(20000);
	          // System.out.println("se va a mover el doc");
	       	//File file = new File("src/main/resources/doc_" + id +".pdf");
			//String nombre = ("doc_" + id + ".pdf");
			//outStream.close();
			//ftpHelper.open();
			//ftpHelper.putFileToFolder(file, nombre);
			//ftpHelper.close();
		}
			return (id);
		}

		public void enviarFTP(long id) throws IOException {
						
		}
		
		@RequestMapping(value = "/enviarBase64PDF", method = RequestMethod.POST)
		public MDocumentoDigital enviarBase64PDF(@Valid @RequestBody String body) throws IOException {

		System.out.println("se llamo al servicio");
		MDocumentoDigital pdf = null;
		//DocumentoDigital pdf = new DocumentoDigital();
		try {

		JSONObject object = new JSONObject(body);
		System.out.println("Antes del id");
		Integer id = object.getInt("id");
		System.out.println("Paso el id");
		pdf = docDigiService.obtenerPorIdDeDocumento(id);
		//pdf.setDocumento("JVBERi0xLjIKNiAwIG9iago8PCAvUyAvR29UbyAvRCAoc2VjdGlvbi4xKSA+PgplbmRvYmoKOCAwIG9iagooSW50cm9kdWNjaVwzNjNuKQplbmRvYmoKMTAgMCBvYmoKPDwgL1MgL0dvVG8gL0QgKHNlY3Rpb24uMikgPj4KZW5kb2JqCjEyIDAgb2JqCihFbCBmdWVudGUpCmVuZG9iagoxNCAwIG9iago8PCAvUyAvR29UbyAvRCAoc2VjdGlvbi4zKSA+PgplbmRvYmoKMTYgMCBvYmoKKEFsZ3Vub3MgZWplbXBsb3MpCmVuZG9iagoxOCAwIG9iago8PCAvUyAvR29UbyAvRCAoc3Vic2VjdGlvbi4zLjEpID4+CmVuZG9iagoyMCAwIG9iagooRXN0byBlcyB1bmEgc3Vic2VjY2lcMzYzbikKZW5kb2JqCjIyIDAgb2JqCjw8IC9TIC9Hb1RvIC9EIChzdWJzdWJzZWN0aW9uLjMuMS4xKSA+PgplbmRvYmoKMjQgMCBvYmoKKEVzdG8gZXMgdW5hIHN1YnN1YnNlY2NpXDM2M24pCmVuZG9iagoyNiAwIG9iago8PCAvUyAvR29UbyAvRCAoc3Vic2VjdGlvbi4zLjIpID4+CmVuZG9iagoyOCAwIG9iagooVGV4dG8gZGUgbXVlc3RyYSkKZW5kb2JqCjMwIDAgb2JqCjw8IC9TIC9Hb1RvIC9EIChzdWJzZWN0aW9uLjMuMykgPj4KZW5kb2JqCjMyIDAgb2JqCihSZWZlcmVuY2lhcyBjcnV6YWRhcyApCmVuZG9iagozNCAwIG9iago8PCAvUyAvR29UbyAvRCAoc3Vic2VjdGlvbi4zLjQpID4+CmVuZG9iagozNiAwIG9iagooRW1wbGVvIGRlIGZ1ZW50ZXMpCmVuZG9iagozOCAwIG9iago8PCAvUyAvR29UbyAvRCAoc3Vic2VjdGlvbi4zLjUpID4+CmVuZG9iago0MCAwIG9iagooTGlzdGFkb3MpCmVuZG9iago0MiAwIG9iago8PCAvUyAvR29UbyAvRCAoc2VjdGlvbi40KSA+PgplbmRvYmoKNDQgMCBvYmoKKE5vdGFzIGRlbCBUcmFkdWN0b3IpCmVuZG9iago0NiAwIG9iago8PCAvUyAvR29UbyAvRCAoc2VjdGlvbi41KSA+PgplbmRvYmoKNDggMCBvYmoKKEFuZXhvOiBFbCBJTlNGTFVHICkKZW5kb2JqCjUwIDAgb2JqCjw8IC9TIC9Hb1RvIC9EIFs0OSAwIFIgIC9GaXQgXSA+PgplbmRvYmoKNTQgMCBvYmogPDwKL0xlbmd0aCA1NSAwIFIKL0ZpbHRlciAvRmxhdGVEZWNvZGUKPj4Kc3RyZWFtCnja7VnbbuM2EAX6mLf9A70UkIGY5VUS92nbJptmmyyKjYsWKPrAyHRWrSy5lJVN9jv2U/qBHV7kyFYSO3srtg0ChPKIHB5yzgw5IxJh+CNRSqNUMiRZlM/3SOT//oy6px9B5jvyJIN2S6ex7TXmGUqJ7frdZO+b51RGFKMkiSYz12sy/S0eH/6h54uyHo1pmsXnRo+ojC9HVMTai6ahPSmqEcFxezWt8/HZ0enJ6PfJi73DyR6OxoShhDlcFGUsMjqarYDAa5oimqxQMBxJJNdAnKrlEmYROP5llMpYl83rfaseOpNVZ4GRFGHAfPrmWd6gvDaVLkukp23ofqN77PsHbHbQZMREbNS0zYupXa8g8aI2ft7neY1GY0ZI/KJurK5IUpSkEUZYuMF/O+EYI5HY/0GqvZrTuloWZamGoHmCKA2gFyqvF3qhnxVVMyvbC1SbiwFsCiNYFkZcEoT3/RQ080BPlXkbwBMpeRhPb5bNMm5tPmYJyqTTctgsnQ1lDKZr57pa1v6nbrxp2+pO6+sbdsBwXYYBzabkYHLgJbfSBBCyiHDEhLM64hYmonx9Z60UYS88rqZFbjFwGR/pShtVdnzrEYsAnWGRwCwvMhfh3aujwDU+4BoZjQnGGGZYmhFJ4xr4kBcOQwIYGMAjdB0YUHq8ktbVJpDUvdvqkQwYJX23u7FtqAYvhi2h4ELgyOxhC6VhoYelp8usBcvrzRkEQ5xsB8+xRAn5EPT8YehZQP9tedFWdeOXENjYbE6UwWi+gwVSgJPdvwg6XAQEURg1JrCI7L5FDOMaQ45tgBx8sPYOrMNa2kp5QdOeN7qjIHRG7Law4zkYpEMOEvAusX0HUiR4f/1DyBAFBSa+wdsb8lG6fEnKNjae0cTGrDt3/q59HvCMI7nTsc4g2vD3ZaPjI8VDPuKOj8TxcY2S4L3kfSjJUsS2ryhBifg4lPxvE41mBFHyGYkGJwNOPNHShxKNhrA3GaXAsBER8dUy3FrcfRL4Nm91szRqE50k9l6wFV6GmNyBNf8HnnzS6AZnHxf/DukeHN1YIN0rPdNGV3mhwlGbm/atmqrBtYHApQa4vf3yg7LdufbIrt3ZxRgSX0pI491NDm6geiOW+av1gF8yRXgHelGbUz7GssdY1mObCGw7KZqlmg4zHgHXph1ACCQ+5TH5yL7d2ZcJlH3OWGfLf++Rd/OQd7+sl93x6Ys8EObgNsd8AW1Zm+FhilfJ5b1JeEIR35KEs49ZSRBdJaHSV/VTX+TraiLHL8+en/x8NFxLisgO6TQTYNR0h7WsF8BWq+Fw2c1uqUrJflUqS21fbHOwXvoFI11RKu1lX+v1T0s4u2MS4bU6IBiyXwcUtJcC+tbVAXl8ae/tYcRNHbBPCF8H7EtOiqpX+nPaDyYHyL/8qdXTrvwxq81cLbUynVKrX6tq2mEKCvN6boVP72QEHLIy3WYoIm1d/R577irb9EFvdQH5CIDoWf1rCANSxs3FvKTLq6X9lcX6StlFIisd2ouCVtIx3BWXVzn6wlg+FM7nIkFRJrYVpkNtCQxOeJd7gQucfX98HLL8wkHx7nAWrLywBgqV8W5Kr0fNz0M1IMvsqXbL9KJfFw9MOlE+A/w1VLF/mHhWkPg6bECy2oAM7kFd4Xupr4pqVg82CRwm46uTa+hYLOG23t5zrLUqKJe9KuhGuO07CvRlSRLX5402l9YVlPESHd4ELe55GlrddJKv8tfa1PY5jUGD37dEIMq27ZvyCooKUmOIsoV3Q4rj2r9YKBO6zGubPRs/Se6ngH3A5LZCDe8XauYBWdt0q3IFf2VcvtRfUdkJtIfTGi9Ivb97QH+12u+n/c6TWmr2PrmshQMU4oE+D3QrtTZN4FuPYRzuNnwHhnkbpisbEuLq64N5A/eOWh9OGaKpU5T01GNEZbSSPQnu0zlD27SwPUM6ih5l97sh4WhRJn9d2I0N9tukuyBIpGHsRRsM6L5w2WpzD5nDmgVct8cO6xai7xbgCVIi0aU6bktcET0hq2TF/Wjqyj9c2wZbgunceW9CbYwoShCEvqr07ZpTw+/cUco+dfEDHv3hAea1IYbTm+kXDh/NfAVnSxQzRs26gY3uWusFAfZcTwvlXNECLsM2Cnvj3tCNO7N74ZNKq6BYB13nparyet8j4ZihLOtz+TqQtrsWzVVu6nBydizO67LOVQh+sM1Gd9H2YvUR491cXcP1CUgxhjPYf4AkMbjRuxCND4PScwV3f7+2XsDePAe7Y4NhWzj7kE/H/wC9yas+ZW5kc3RyZWFtCmVuZG9iago1NSAwIG9iagoxNzA5CmVuZG9iago0OSAwIG9iaiA8PAovVHlwZSAvUGFnZQovQ29udGVudHMgNTQgMCBSCi9SZXNvdXJjZXMgNTMgMCBSCi9NZWRpYUJveCBbMCAwIDU5NS4yNyA4NDEuODldCi9QYXJlbnQgNzMgMCBSCi9Bbm5vdHMgWyA2MCAwIFIgNjEgMCBSIDYyIDAgUiA2MyAwIFIgNjQgMCBSIDY1IDAgUiA2NiAwIFIgNjcgMCBSIDY4IDAgUiA2OSAwIFIgNzAgMCBSIF0KPj4gZW5kb2JqCjEgMCBvYmoKIDw8IC9UeXBlIC9FbmNvZGluZyAvRGlmZmVyZW5jZXMgWyAyNCAvYnJldmUgL2Nhcm9uIC9jaXJjdW1mbGV4IC9kb3RhY2NlbnQgL2h1bmdhcnVtbGF1dCAvb2dvbmVrIC9yaW5nIC90aWxkZSAzOSAvcXVvdGVzaW5nbGUgOTYgL2dyYXZlIDEyOCAvYnVsbGV0IC9kYWdnZXIgL2RhZ2dlcmRibCAvZWxsaXBzaXMgL2VtZGFzaCAvZW5kYXNoIC9mbG9yaW4gL2ZyYWN0aW9uIC9ndWlsc2luZ2xsZWZ0IC9ndWlsc2luZ2xyaWdodCAvbWludXMgL3BlcnRob3VzYW5kIC9xdW90ZWRibGJhc2UgL3F1b3RlZGJsbGVmdCAvcXVvdGVkYmxyaWdodCAvcXVvdGVsZWZ0IC9xdW90ZXJpZ2h0IC9xdW90ZXNpbmdsYmFzZSAvdHJhZGVtYXJrIC9maSAvZmwgL0xzbGFzaCAvT0UgL1NjYXJvbiAvWWRpZXJlc2lzIC9aY2Fyb24gL2RvdGxlc3NpIC9sc2xhc2ggL29lIC9zY2Fyb24gL3pjYXJvbiAxNjQgL2N1cnJlbmN5IDE2NiAvYnJva2VuYmFyIDE2OCAvZGllcmVzaXMgL2NvcHlyaWdodCAvb3JkZmVtaW5pbmUgMTcyIC9sb2dpY2Fsbm90IC8ubm90ZGVmIC9yZWdpc3RlcmVkIC9tYWNyb24gL2RlZ3JlZSAvcGx1c21pbnVzIC90d29zdXBlcmlvciAvdGhyZWVzdXBlcmlvciAvYWN1dGUgL211IDE4MyAvcGVyaW9kY2VudGVyZWQgL2NlZGlsbGEgL29uZXN1cGVyaW9yIC9vcmRtYXNjdWxpbmUgMTg4IC9vbmVxdWFydGVyIC9vbmVoYWxmIC90aHJlZXF1YXJ0ZXJzIDE5MiAvQWdyYXZlIC9BYWN1dGUgL0FjaXJjdW1mbGV4IC9BdGlsZGUgL0FkaWVyZXNpcyAvQXJpbmcgL0FFIC9DY2VkaWxsYSAvRWdyYXZlIC9FYWN1dGUgL0VjaXJjdW1mbGV4IC9FZGllcmVzaXMgL0lncmF2ZSAvSWFjdXRlIC9JY2lyY3VtZmxleCAvSWRpZXJlc2lzIC9FdGggL050aWxkZSAvT2dyYXZlIC9PYWN1dGUgL09jaXJjdW1mbGV4IC9PdGlsZGUgL09kaWVyZXNpcyAvbXVsdGlwbHkgL09zbGFzaCAvVWdyYXZlIC9VYWN1dGUgL1VjaXJjdW1mbGV4IC9VZGllcmVzaXMgL1lhY3V0ZSAvVGhvcm4gL2dlcm1hbmRibHMgL2FncmF2ZSAvYWFjdXRlIC9hY2lyY3VtZmxleCAvYXRpbGRlIC9hZGllcmVzaXMgL2FyaW5nIC9hZSAvY2NlZGlsbGEgL2VncmF2ZSAvZWFjdXRlIC9lY2lyY3VtZmxleCAvZWRpZXJlc2lzIC9pZ3JhdmUgL2lhY3V0ZSAvaWNpcmN1bWZsZXggL2lkaWVyZXNpcyAvZXRoIC9udGlsZGUgL29ncmF2ZSAvb2FjdXRlIC9vY2lyY3VtZmxleCAvb3RpbGRlIC9vZGllcmVzaXMgL2RpdmlkZSAvb3NsYXNoIC91Z3JhdmUgL3VhY3V0ZSAvdWNpcmN1bWZsZXggL3VkaWVyZXNpcyAveWFjdXRlIC90aG9ybiAveWRpZXJlc2lzIF0gPj4gCmVuZG9iagoyIDAgb2JqCiA8PCAvVHlwZSAvRm9udCAvU3VidHlwZSAvVHlwZTEgL05hbWUgL1phRGIgL0Jhc2VGb250IC9aYXBmRGluZ2JhdHMgPj4gCmVuZG9iagozIDAgb2JqCiA8PCAvVHlwZSAvRm9udCAvU3VidHlwZSAvVHlwZTEgL05hbWUgL0hlbHYgL0Jhc2VGb250IC9IZWx2ZXRpY2EgL0VuY29kaW5nIDEgMCBSID4+IAplbmRvYmoKNCAwIG9iagogPDwgL0ZpZWxkcyBbXSAvRFIgPDwgL0ZvbnQgPDwgL1phRGIgMiAwIFIgL0hlbHYgMyAwIFIgPj4gPj4gL0RBICgvSGVsdiAxMCBUZiAwIGcgKSAvTmVlZEFwcGVhcmFuY2VzIHRydWUgPj4gCmVuZG9iago2MCAwIG9iaiA8PAovVHlwZSAvQW5ub3QKL0JvcmRlciBbMCAwIDBdL0ggL0kvQyBbMSAwIDBdCi9SZWN0IFs3MiA1OTYuOTQgMTQyLjEyIDYwNC4zXQovU3VidHlwZSAvTGluawovQSA8PCAvUyAvR29UbyAvRCAoc2VjdGlvbi4xKSA+Pgo+PiBlbmRvYmoKNjEgMCBvYmogPDwKL1R5cGUgL0Fubm90Ci9Cb3JkZXIgWzAgMCAwXS9IIC9JL0MgWzEgMCAwXQovUmVjdCBbNzIgNTY4LjIgMTI1LjQxIDU3NS4yXQovU3VidHlwZSAvTGluawovQSA8PCAvUyAvR29UbyAvRCAoc2VjdGlvbi4yKSA+Pgo+PiBlbmRvYmoKNjIgMCBvYmogPDwKL1R5cGUgL0Fubm90Ci9Cb3JkZXIgWzAgMCAwXS9IIC9JL0MgWzEgMCAwXQovUmVjdCBbNzIgNTM3LjU3IDE2MS45NCA1NDYuNDZdCi9TdWJ0eXBlIC9MaW5rCi9BIDw8IC9TIC9Hb1RvIC9EIChzZWN0aW9uLjMpID4+Cj4+IGVuZG9iago2MyAwIG9iaiA8PAovVHlwZSAvQW5ub3QKL0JvcmRlciBbMCAwIDBdL0ggL0kvQyBbMSAwIDBdCi9SZWN0IFs4Ni45NCA1MjAuNjggMjAxLjQ0IDUyNy42N10KL1N1YnR5cGUgL0xpbmsKL0EgPDwgL1MgL0dvVG8gL0QgKHN1YnNlY3Rpb24uMy4xKSA+Pgo+PiBlbmRvYmoKNjQgMCBvYmogPDwKL1R5cGUgL0Fubm90Ci9Cb3JkZXIgWzAgMCAwXS9IIC9JL0MgWzEgMCAwXQovUmVjdCBbMTA5Ljg2IDUwMS45MSAyNDcuMTYgNTA4Ljg5XQovU3VidHlwZSAvTGluawovQSA8PCAvUyAvR29UbyAvRCAoc3Vic3Vic2VjdGlvbi4zLjEuMSkgPj4KPj4gZW5kb2JqCjY1IDAgb2JqIDw8Ci9UeXBlIC9Bbm5vdAovQm9yZGVyIFswIDAgMF0vSCAvSS9DIFsxIDAgMF0KL1JlY3QgWzg2Ljk0IDQ4My4xMyAxNzguMTggNDkwLjA2XQovU3VidHlwZSAvTGluawovQSA8PCAvUyAvR29UbyAvRCAoc3Vic2VjdGlvbi4zLjIpID4+Cj4+IGVuZG9iago2NiAwIG9iaiA8PAovVHlwZSAvQW5ub3QKL0JvcmRlciBbMCAwIDBdL0ggL0kvQyBbMSAwIDBdCi9SZWN0IFs4Ni45NCA0NjQuMzUgMTk2LjcxIDQ3MS4yOV0KL1N1YnR5cGUgL0xpbmsKL0EgPDwgL1MgL0dvVG8gL0QgKHN1YnNlY3Rpb24uMy4zKSA+Pgo+PiBlbmRvYmoKNjcgMCBvYmogPDwKL1R5cGUgL0Fubm90Ci9Cb3JkZXIgWzAgMCAwXS9IIC9JL0MgWzEgMCAwXQovUmVjdCBbODYuOTQgNDQzLjU2IDE4NC4wMSA0NTIuNTFdCi9TdWJ0eXBlIC9MaW5rCi9BIDw8IC9TIC9Hb1RvIC9EIChzdWJzZWN0aW9uLjMuNCkgPj4KPj4gZW5kb2JqCjY4IDAgb2JqIDw8Ci9UeXBlIC9Bbm5vdAovQm9yZGVyIFswIDAgMF0vSCAvSS9DIFsxIDAgMF0KL1JlY3QgWzg2Ljk0IDQyNi44IDE0My42MiA0MzMuNzNdCi9TdWJ0eXBlIC9MaW5rCi9BIDw8IC9TIC9Hb1RvIC9EIChzdWJzZWN0aW9uLjMuNSkgPj4KPj4gZW5kb2JqCjY5IDAgb2JqIDw8Ci9UeXBlIC9Bbm5vdAovQm9yZGVyIFswIDAgMF0vSCAvSS9DIFsxIDAgMF0KL1JlY3QgWzcyIDM5OC4wMiAxNzIuNTQgNDA1LjA3XQovU3VidHlwZSAvTGluawovQSA8PCAvUyAvR29UbyAvRCAoc2VjdGlvbi40KSA+Pgo+PiBlbmRvYmoKNzAgMCBvYmogPDwKL1R5cGUgL0Fubm90Ci9Cb3JkZXIgWzAgMCAwXS9IIC9JL0MgWzEgMCAwXQovUmVjdCBbNzIgMzY5LjI4IDE3OS4xNSAzNzYuMzNdCi9TdWJ0eXBlIC9MaW5rCi9BIDw8IC9TIC9Hb1RvIC9EIChzZWN0aW9uLjUpID4+Cj4+IGVuZG9iago1MiAwIG9iaiA8PAovRCBbNDkgMCBSIC9YWVogNzIgNzkzLjkzIG51bGxdCj4+IGVuZG9iago1MSAwIG9iaiA8PAovRCBbNDkgMCBSIC9YWVogNzIgNzYwLjQ1IG51bGxdCj4+IGVuZG9iago1IDAgb2JqIDw8Ci9EIFs0OSAwIFIgL1hZWiA3MiAzNTMuNTkgbnVsbF0KPj4gZW5kb2JqCjkgMCBvYmogPDwKL0QgWzQ5IDAgUiAvWFlaIDcyIDIyNC45IG51bGxdCj4+IGVuZG9iago1MyAwIG9iaiA8PAovRm9udCA8PCAvRjI5IDU2IDAgUiAvRjMwIDU3IDAgUiAvRjMxIDU4IDAgUiAvRjMyIDU2IDAgUiAvRjMzIDU5IDAgUiAvRjM0IDU5IDAgUiAvRjM1IDcxIDAgUiAvRjM2IDcxIDAgUiAvRjM3IDcyIDAgUiA+PgovUHJvY1NldCBbIC9QREYgL1RleHQgXQo+PiBlbmRvYmoKNzcgMCBvYmogPDwKL0xlbmd0aCA3OCAwIFIKL0ZpbHRlciAvRmxhdGVEZWNvZGUKPj4Kc3RyZWFtCnja3VnNktu4Ea7KcW77BrqZqrK4BAH+bQ6pzcaxnUx2nPUkqVSSA0RixtylSBkUNx4/hw95kNzzaulGNyhK1M/kmtKBJH4bje6vv26JRQQ/scjiRVbIsJCLcnMjFvT7aeHffn8TLVbQnS9Umi+iMFlYs3i4+fX9zde/lWpRhEW6uH9wa91XfwtkuFwlaRR82zwObdcvV3EiAvOj2Wwb+PrH/e9gVjTOUqkMo5inxth98+oehCDJ3IbnpPKDVjhqpWSoEhxKcsmFUKFMDgRbrkQUTQVTxXnB4MxxEUa5m/rG4DGiQH8ccOAizsMYhA6jxHX/2zVGYZwtVmPjVzzlpBrcV8WrmsZsTLuj5jj4OHB7b6xbWKQijNTxdrBTkkz20y2vBjsYXY1btvxsqPthgK0M3JEUInhn642x3UvqqkxfmrbSGy+Jpvah5Zd+WPemLGvSQRqFQpyQKpcTqbr2G1KtgksTrNuVUqDAFKwqCdOYrUYsV0VRBK/6XcdX00+3h4aD7YWE8+MdCDXdXuDe3NS1s1tdCbhUmAYLhyTgd92mQ2WowJrPmt5QZ1LIoOHvUq9NaaxGy45E8D0JEEehTK+ef2d6Q6u4e8VlfcPWmrLueY+h15Z3b2hY2W10W3V8hnQ8g0hkmEg26u3siEUofJ+2/gAdGNjn2QaDsVs+fMUy+SNPFK3SMFbX7xmMSMZFsLO6H7dxI1WchQl4hpBhKt3gcyeT4HBeeBBgJ2aHg9vLCx7hbDhi3xSjb0oZ5s9zTTQs2iDbbxCj9bAIYG9TkwOjVW6V7EgRzguyczbnnrQi+8IENVcij8MUXUE6uCJXQGcArBLeG9Ct2Z8PnPHQIWBagQ4Rn7onbj3pE9JZ8t4n7n5CS1d58EY/gZJlFCR0uW29jJPg56VIELR66nOmA51OlK4dm+t+27X1Gsa51cC1HTJZ6nYoiC99/TjUiEn8zcbRz60D5csn5jG3DohS3n5ezuYn+3u4blwnp2eT6fH/Pn26u7wyfSVBYU+zVVYqydCKJ86Eq6nZajIO8+QAB2IA1269M62xjcYrUYlC+zLUVXXl4KIQfVIUwfecQge29bu6mXttHIm95Nru6rIx8zivnJu4MRTgcOGennpru20NMYv22cv75m4pk+Av90uRB3c8+Ike3c66MMWir8ja46xwUXGvHoqsv4SRMqOTyOjcSdIMoxIJac22s3MTg4iVp/tbiqUK/h4lER0JVq7bshme+MNv5/HOfVTcOfXcLBTJdYSdR4LYITNh6ge93V00KpBTeBHWjhZI4hjuhVhJXBzwB8n8AZoxMLi5bCcafZ2VnosjgK8827j9zbulAJAO5yQgovAvGPNiCv/3yyIOzCfPAZyy4LkZ4MqsPsnSPGrdL/Mo6JyaEwkgBUil6X0N+OI4jgq0w5VFqpB4zKNEfhwlRjqmHFARCstgZ8DI8U7dsokzSmj+CEhm/RigUSCypcklM7liHpxmF13Vj3yIirdm3shn4M6hpSd3Uh/NkMHbr+/opezaw+Hga49WbzRL3vEdYtg8DNKDbtx5KO6UXa+ZNf6p5xDETDYKvqCTWaC5X+Y2qoCneRMsu2oODXEaeiOeu2QWKo+6Pxu7vjSZYcNx3cZz2mP6W0OgsXVnDxn44LkzHeME5Yr2ntaX1pj2KjI4nW3G6L0z3xxnN+gBEcSF+FqGIwocdCERem4bZ1VhUdBqlCslixxj2yRVorCQMESnEWkoKYq9sWFnZbiR1eYaX7zAi3rxYs4zYoXhGeAizMjE7kg5O71ZExJC1IIs9EqiY9oTOvWLg7UpzlMV5aljmsgj4Cql/D/TOPoVaXyqCxFm+WVdAGGC7lGsaJbMv2qIiZxzDMwNfCqyO+MYKgmlz/D7GqMLxg9DC1fmFy2/4oHxCeag8WiS8R+flLXS+9YgJDs4LSDH35vLv07CaYtQIDMJrl9h3ALQRm3KhJkr0NyHzm40La4BGysNpDXEW0iD71kQ0/tYl2C9YoKTLaSGkLvVHfm8R6HIHa22nrX7bPwMwEi33vOArrPz+VGYXQbZA2rs5NtC5u9TiceaP4SPd8Klqdj7QT+6BDzxwVMIecJNj6NnSAqTEZi6wjwHrRF7budZFyzoD3dbt8MnIBmr96//cIuSAh94TZld7qwVt0gP98Wsh9u+csyRkb0AL+oHdzfH+khSFHfPtsHhzBKS1k/bpi55DeapwN/gTssdR3bkJ/0WMnfd0Dfc+WAqh0rw/kSPtpt3EdcqDks0sNxa/8ijB2ZUmOKnTGNjBr3ThsOI+Sy7eboUXa9azQkKtyrA7MRhGUcSj/vBPMBpBSIHaIqLbaUdPoN39Rdp3F/R6vLgP77UpsLsakSgKR+0o2GQiXZra+i1cXtDp0WBRmHSaBTmV5h2JgjAmmfviXkhwqh4BjHn7Xl+TRwUWKu2JWxBH6UfR1SkOF/fAcDMPWA2ek11lLO0HlObVPKqORg8bz5e5wStZZioMb95mC+Lxd2IUZMBD7LEUKRTwMNkrbNI//VBSUJMdMz8h1Q8Y0ONPoCayN/chK5xjP/yZ0gf4NN6SBqrj5DoPaf6eMy5YjRZhCM4a+ZCH7XbRx7ww+uzwRCN+2g5yMBUcr1EDaMO4v98bUwiMUH7smexG937OrA7XJKHMjsV7dQ02mFqT8CbQlIlpsD7RrONi0B/6Kx+6W+jP76+/uD++KvtfAW5dZe/1u1hibnhwAdZT9u7mOovK08dBXiOH0WnDBdAQHrDbW338HCq3iHzWSIAlEEkwSdfQ/v2/Xdv37IlOSJyCtOkip3epqCmuDaNc44yU2ImlyHtj2NamGZ+Aio/i124SFO+A+jF+gwkjphpAUa9c4kKNPfDFjNg3DvN6SZgloaTAvtoqZX9C0c7VcKL4ae7GZhAlTvbM9sW6fPqDm4Nrzx4pfTeScv6dacRnlJgT1f5I0E25l+ZP6jCkZ0r2TfBT5ogw5zWu7ydbCBiNd484xEyxqSUKgC23v8X4mxyd/z3S6+butLz0mwcxXurW3dN9aBLcyrtG+uCL2fERuHfZtQJQf+D7uu5pcgM/2Y6XCGeruCRvge3Qj3nxCRA8/XcEcB6syN51OnVGg12WM2DAP23daaMOTnQ7mlr/mnrnbFzdlUg5hywTTMnfZOyYb3zJYW67E9xmLGYecplVaocCk7rSQm57G0NmFd1l/3z1plEBAjmR7svsrQopgTV2Re0PpANR5Kq7Zf/kytrKn/HhQre73Mf1ImIiQcaWta5lHvSn4FzWgB4niWjvsym/nyizCpREZ7RtYdLnyMcoD0xWfdq7iDGWB5xlgDPbg1GCS6nAs3xp8ixZjLxXP1xqGdFEFcCQVofQ6KQXC2FXPxH+L9APMRJZW5kc3RyZWFtCmVuZG9iago3OCAwIG9iagoyNTMxCmVuZG9iago3NiAwIG9iaiA8PAovVHlwZSAvUGFnZQovQ29udGVudHMgNzcgMCBSCi9SZXNvdXJjZXMgNzUgMCBSCi9NZWRpYUJveCBbMCAwIDU5NS4yNyA4NDEuODldCi9QYXJlbnQgNzMgMCBSCi9Bbm5vdHMgWyA3OSAwIFIgXQo+PiBlbmRvYmoKNzkgMCBvYmogPDwKL1R5cGUgL0Fubm90Ci9Cb3JkZXIgWzAgMCAwXS9IIC9JL0MgWzEgMCAwXQovUmVjdCBbMzYyLjc0IDI0Ny42MSAzNzUuMTkgMjU2LjYxXQovU3VidHlwZSAvTGluawovQSA8PCAvUyAvR29UbyAvRCAoc3Vic2VjdGlvbi4zLjMpID4+Cj4+IGVuZG9iago3NCAwIG9iaiA8PAovRCBbNzYgMCBSIC9YWVogNzIgNzkzLjkzIG51bGxdCj4+IGVuZG9iagoxMyAwIG9iaiA8PAovRCBbNzYgMCBSIC9YWVogNzIgNzYwLjQ1IG51bGxdCj4+IGVuZG9iagoxNyAwIG9iaiA8PAovRCBbNzYgMCBSIC9YWVogNzIgNzA0LjY3IG51bGxdCj4+IGVuZG9iagoyMSAwIG9iaiA8PAovRCBbNzYgMCBSIC9YWVogNzIgNjI5LjkyIG51bGxdCj4+IGVuZG9iagoyNSAwIG9iaiA8PAovRCBbNzYgMCBSIC9YWVogNzIgNTMyLjIzIG51bGxdCj4+IGVuZG9iagoyOSAwIG9iaiA8PAovRCBbNzYgMCBSIC9YWVogNzIgMzA3Ljc5IG51bGxdCj4+IGVuZG9iagozMyAwIG9iaiA8PAovRCBbNzYgMCBSIC9YWVogNzIgMjE0LjI3IG51bGxdCj4+IGVuZG9iagozNyAwIG9iaiA8PAovRCBbNzYgMCBSIC9YWVogNzIgMTM5LjYyIG51bGxdCj4+IGVuZG9iago3NSAwIG9iaiA8PAovRm9udCA8PCAvRjM0IDU5IDAgUiAvRjMwIDU3IDAgUiAvRjMzIDU5IDAgUiAvRjQxIDU5IDAgUiAvRjM2IDcxIDAgUiAvRjM3IDcyIDAgUiAvRjM1IDcxIDAgUiAvRjMyIDU2IDAgUiAvRjQyIDgwIDAgUiA+PgovUHJvY1NldCBbIC9QREYgL1RleHQgXQo+PiBlbmRvYmoKODYgMCBvYmogPDwKL0xlbmd0aCA4NyAwIFIKL0ZpbHRlciAvRmxhdGVEZWNvZGUKPj4Kc3RyZWFtCnjazVlLk9u4Ea7a3HzZyj/QKUtVWQhBAHw4h8TZsfcR2+uUx3tJcuBQGC0ditTyYY/3b2QrlR+Se/5autENihpqJFU2qWxN1RAEgUY/v+6G5CKEP7lIokWSKZGpRbF9JBf099eFH/3hUbhYwed0oeN0EQqzaO3i9tHvrx/9+rnSi0xk8eL61tG6Xv8p0GK5MnEYvGr6vFuuIiODta1wEAbXy0QFbb4eir5pl3+5/hoohCMFHSsRRkxG4edHz66BIeLSHf4Qh37RClettBLanFsqtcg0UXSiyLkon854QC2cZQJWZRPCEwk94Wdd35BGbEfPoSZVVWXX5+vm/sGrCIjiQ4r45yzYKxbru/wjDep8nZNkdilNcFeUfV73lqdqVkJVNeI+S6GT1mRnxZUiM1Ou5uL+/T8WNz0tLvhzFuTbmxIPWERGJAkESGjcx3+6yRUEjMH/POtl7iw/m13Tgk5II1u3J05FeIxQqiaEhqovd5X3H1vZra37phNz15HOdWQi4ujnrMxXg11GOni/jAzoFISxj0kpNTtV3TCedE27a229tg8KG6kLPCcTOj7NkpwdkAid/DeEfUFx3vlAGLa29e9RUDQ1o2M87pShEknM23HDDD+jWGj+3u+dUonIXOqUt0NdlE2d1ye9SP50xUb/M8Ve2a5oyx2K4WJDhZB+4BmlAcZH65wJX7YQPHlNUHuoaJ258HPk1kRunqu0kD5VvRuA8IxMFInEjObYzK0VCk9gN9i1M0GUAS60UwbXeYdRoBT4xLahJfn3g7OiVKFQ900LVNOJZX9JxNwJNHyPOGzb7ljwxCK7MHbup4I5Trxuy62TBfyq7O12dpzRIpIXpHQVgZQraUSsThn+S04qXjtRKqLoAu2MyfcBNlkrFzn+ea28sZsBnc6xevS8GIyqLlFLKnREeolO6eWp95ZYpNkRfSRzfXD2lkHTt80JfUQ/XR/XyywCb1zKNChOe4vEmu68WqJMGH2BWv717VLKEBJNwxk0pwdkY8Zkrll72wJnzW9netCg0OjCcPl/1mRvJ95No0/qvCIhd3nLcudFfpO3FRcQ+4IzFYme1KwqMa5mVUkcdCVClMvUNNE3a15S8fP7gT91liZqW9gOakCapeNxfgdw3Xa8GLEQJ7d5W3zHSx0O35S2piPiYN0UA5U89P7mi5cvHvPaB7EdikqpEEhQoqqshzsgs+o222qGz+ken6+urwRp6bX3jtslOs8yCrFeCQOY1mHw2IfPD1tbcYx3+Y33665kFwMpOt8bOQ3tC0JslnCDQzCIMXkOwdh8BSb8nJlrvEfjBhM7P/Ib/nG0mIQyveTNebVpDiLCdj2zOKpcsLYUOrYyqK6VMlCfAE0tkUPXCS5XMgz3naDOuBOEAVTO+uFOMHRxHBKZ15iwyE+1Yn1pHVREUwV9WUGWRt1r8E0nXhqJUJ+V2TKBj/RYW6q+NayT5yomf/hYdxNTUJI3G7JekhzB2xmZT4qGKRUgYtGz6dFo8hxYd31Z+INddgcq9QDmahuaLNdls81pnEOs2R8K12jga0Xrd20DAekC32kQA40BwBiElkm8QM1dlB3STjF0O+duqSGkhCecQJKnF/RBUOETn7DxM3qsqoPXnF8xOqO7uzs6l+yP0/x0we5ahcwEN3mH2ILzWEMTWwgtlVMU7O892WLwI1sfynE7IKT9BrAkVOPkIRcd+dkqcUXGREe2BjsuZRJsWBlKY91wThkcX3baKu94tobQrHynwHN/+9XdXTH09kfe0BdCHA1KLcJ4GpOGY/Jpbe+aJyhiFjzjmPzq1ZvnL95+8VA0ZpQGPFIm+4JZitg3Jg/R0JPm5bZpnVemEbqMAxcYEjTAYNMOu4aGJdihrXPXkxw5VxshzdhQAZjTriuGqbwvyQcUFKNLAIfmnS36GWtSgr9mTAb9KM0mZiQjRvNCG20YT20I+aYbZaEnYRQMegd1Y1MCHJE8CJtSyKkHFeDCtqpy16jEhmjFgHfOBWDiywY75A+9f/9zaMLPoTnoYCCR/zhFeHI1nwmFvKToA/rcXwDBKqcZwAbHNAU1FFTpuTsJp+4Jz9McjfNNW25KMKVTQkyJHtdBzY53QLwKNOCHfgF/0xz+8KVuGKYiI9SBAil6ys7fMuU12dBgYXguEKvGZz/LVzJlvSFTmUiY9JwXWF8/pYkIkS3wLYq8Z0BPqxQBhTxQTxt3V+qdDKBUxN7X0c2QFKgT3RxfMkTnW9sicnFFhpM5Laz46d2QGwJgUV1iUqS05jOnJsX5m9aiO1JXiTlEO+xFX8LPaLhZ3EJ2G+95P//m5TfdTFqVoFppxccZgQzhjbvMt8/nu1ca2nOAG+cUkVuHQTLTuxLKs/F6RiTG+oM+gohSB9C48Y22Q+r7xHRClbgruWfUkrGY7JrZVgBQ5W9unh9jJBsZKYbJxViVz5ULXhqlIy0JfD/F0vSPcy1FUvhbDjErlI3zdffxCeLKHDUNekjolSu59sVMRH4kkxgjchIBV2XL9xYYGmdA6V3ub0hzL6yvk9e+HLXcxfiYudfSUDkn0RcuKuewR6pdcuIIAfRU5iLMQzaZmdZ2O0gzje+jwhivVGdAEHFQKhYIZ5xAODUKhC+Qi5oaIpeVp7NL6koi2JVQHbWW6Oy9Ze95scT6IMR/E2KQkaQjFo83zdv8SJAakXoX8LdKnOHwvPXkXMfNNAk+YWpy71AqHP3xw4cPoqy722rYiKad352lmYgPfBe7cXDZgzzwtHOZYMO9lJDxMVPq6ZU62A5bUBU75vEJSAZp8AZLXfdKdymZcvB0LpfgHm6XYW9F/ZiCveqSy32skXDfqFrqTlKn9PM+6aQoO6h+y5uKpXGNtaJKF9+/qrtfDBsa488yHX32wt/k77zgA+8c4f9QTf4z3l7KLFixH2UaOZrA8Pty7Tto7nEToc56s91VZZH7gIqd0fbx9AZ50JgA8acUVyvCBN7cjJfgKZTp2SWX4EhncPth4H6Lo+Gaz3B1CA5AUCeLUxmcxcEJ4oTpZeIQnUle2mM4RMKIvtuyhdpVB0e6ZNCEmkKwZ7WiwWjcEQoh2i+ADpawsC10iw3L59hNg2/Xwt2x6IAVcgiYElm6pKSgkDUptumTkG1tBUU71ROR9s0OP/AykmEa82Db7X89oee+ciZXCclLEsqFbV5D91rwtczXVJfgJbRxuUgfVYnmitKd+hJguAT6j2fYpWO6ynZdcl40O7uzvzsFYFJmeMQEwY792quTBK8Nz90Anvph/N+ags04ZW5kc3RyZWFtCmVuZG9iago4NyAwIG9iagoyNDU2CmVuZG9iago4NSAwIG9iaiA8PAovVHlwZSAvUGFnZQovQ29udGVudHMgODYgMCBSCi9SZXNvdXJjZXMgODQgMCBSCi9NZWRpYUJveCBbMCAwIDU5NS4yNyA4NDEuODldCi9QYXJlbnQgNzMgMCBSCj4+IGVuZG9iago4MyAwIG9iaiA8PAovRCBbODUgMCBSIC9YWVogNzIgNzkzLjkzIG51bGxdCj4+IGVuZG9iago4MSAwIG9iaiA8PAovRCBbODUgMCBSIC9YWVogNzIgNjc5LjU1IG51bGxdCj4+IGVuZG9iago4MiAwIG9iaiA8PAovRCBbODUgMCBSIC9YWVogNzIgNjYzLjk2IG51bGxdCj4+IGVuZG9iago0MSAwIG9iaiA8PAovRCBbODUgMCBSIC9YWVogNzIgNDU4Ljk4IG51bGxdCj4+IGVuZG9iago0NSAwIG9iaiA8PAovRCBbODUgMCBSIC9YWVogNzIgMzYxLjM1IG51bGxdCj4+IGVuZG9iago4NCAwIG9iaiA8PAovRm9udCA8PCAvRjM0IDU5IDAgUiAvRjMwIDU3IDAgUiAvRjE0IDg4IDAgUiAvRjM2IDcxIDAgUiAvRjMzIDU5IDAgUiAvRjM3IDcyIDAgUiAvRjMxIDU4IDAgUiA+PgovUHJvY1NldCBbIC9QREYgL1RleHQgXQo+PiBlbmRvYmoKODkgMCBvYmogPDwKL0xlbmd0aCA5MCAwIFIKL0ZpbHRlciAvRmxhdGVEZWNvZGUKPj4Kc3RyZWFtCnjaMzFSMFAwVTBTMDYHoRRDrkIuY0OgmIECkAJJJOdyOXly6YcD+Vz6HmDS01ehpKg0lUvfKcBZAch3UYgGaonl8nRRYJD/wMDw/x8D4///DOz//x/g////gfz//x/s////AcL1////geH/////I4SR1cPMAJkHMhdkPsgekH0ge7lcPbkCuQCL2XIqZW5kc3RyZWFtCmVuZG9iago5MCAwIG9iagoxNDAKZW5kb2JqCjg4IDAgb2JqIDw8Ci9UeXBlIC9Gb250Ci9TdWJ0eXBlIC9UeXBlMwovTmFtZSAvRjE0Ci9Gb250TWF0cml4IFswLjAxMjA0OCAwIDAgMC4wMTIwNDggMCAwXQovRm9udEJCb3ggWyAwIDAgMzcgMzcgXQovUmVzb3VyY2VzIDw8IC9Qcm9jU2V0IFsgL1BERiAvSW1hZ2VCIF0gPj4KL0ZpcnN0Q2hhciAwCi9MYXN0Q2hhciAxMjcKL1dpZHRocyA5MSAwIFIKL0VuY29kaW5nIDkyIDAgUgovQ2hhclByb2NzIDkzIDAgUgo+PiBlbmRvYmoKOTEgMCBvYmoKWyAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCA0MSAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIF0KZW5kb2JqCjkyIDAgb2JqIDw8Ci9UeXBlIC9FbmNvZGluZwovRGlmZmVyZW5jZXMgWyAwIC9hMC9hMS9hMi9hMy9hNC9hNS9hNi9hNy9hOC9hOS9hMTAvYTExL2ExMi9hMTMvYTE0L2ExNS9hMTYvYTE3L2ExOC9hMTkvYTIwL2EyMS9hMjIvYTIzL2EyNC9hMjUvYTI2L2EyNy9hMjgvYTI5L2EzMC9hMzEvYTMyL2EzMy9hMzQvYTM1L2EzNi9hMzcvYTM4L2EzOS9hNDAvYTQxL2E0Mi9hNDMvYTQ0L2E0NS9hNDYvYTQ3L2E0OC9hNDkvYTUwL2E1MS9hNTIvYTUzL2E1NC9hNTUvYTU2L2E1Ny9hNTgvYTU5L2E2MC9hNjEvYTYyL2E2My9hNjQvYTY1L2E2Ni9hNjcvYTY4L2E2OS9hNzAvYTcxL2E3Mi9hNzMvYTc0L2E3NS9hNzYvYTc3L2E3OC9hNzkvYTgwL2E4MS9hODIvYTgzL2E4NC9hODUvYTg2L2E4Ny9hODgvYTg5L2E5MC9hOTEvYTkyL2E5My9hOTQvYTk1L2E5Ni9hOTcvYTk4L2E5OS9hMTAwL2ExMDEvYTEwMi9hMTAzL2ExMDQvYTEwNS9hMTA2L2ExMDcvYTEwOC9hMTA5L2ExMTAvYTExMS9hMTEyL2ExMTMvYTExNC9hMTE1L2ExMTYvYTExNy9hMTE4L2ExMTkvYTEyMC9hMTIxL2ExMjIvYTEyMy9hMTI0L2ExMjUvYTEyNi9hMTI3IF0KPj4gZW5kb2JqCjkzIDAgb2JqIDw8Ci9hMTUgODkgMCBSCj4+IGVuZG9iago5NCAwIG9iaiA8PAovVHlwZSAvRW5jb2RpbmcKL0RpZmZlcmVuY2VzIFsgMC8ubm90ZGVmIDEvZG90YWNjZW50L2ZpL2ZsL2ZyYWN0aW9uL2h1bmdhcnVtbGF1dC9Mc2xhc2gvbHNsYXNoL29nb25lay9yaW5nIDEwLy5ub3RkZWYgMTEvYnJldmUvbWludXMgMTMvLm5vdGRlZiAxNC9aY2Fyb24vemNhcm9uL2Nhcm9uL2RvdGxlc3NpL2RvdGxlc3NqL2ZmL2ZmaS9mZmwgMjIvLm5vdGRlZiAzMC9ncmF2ZS9xdW90ZXNpbmdsZS9zcGFjZS9leGNsYW0vcXVvdGVkYmwvbnVtYmVyc2lnbi9kb2xsYXIvcGVyY2VudC9hbXBlcnNhbmQvcXVvdGVyaWdodC9wYXJlbmxlZnQvcGFyZW5yaWdodC9hc3Rlcmlzay9wbHVzL2NvbW1hL2h5cGhlbi9wZXJpb2Qvc2xhc2gvemVyby9vbmUvdHdvL3RocmVlL2ZvdXIvZml2ZS9zaXgvc2V2ZW4vZWlnaHQvbmluZS9jb2xvbi9zZW1pY29sb24vbGVzcy9lcXVhbC9ncmVhdGVyL3F1ZXN0aW9uL2F0L0EvQi9DL0QvRS9GL0cvSC9JL0ovSy9ML00vTi9PL1AvUS9SL1MvVC9VL1YvVy9YL1kvWi9icmFja2V0bGVmdC9iYWNrc2xhc2gvYnJhY2tldHJpZ2h0L2FzY2lpY2lyY3VtL3VuZGVyc2NvcmUvcXVvdGVsZWZ0L2EvYi9jL2QvZS9mL2cvaC9pL2ovay9sL20vbi9vL3AvcS9yL3MvdC91L3Yvdy94L3kvei9icmFjZWxlZnQvYmFyL2JyYWNlcmlnaHQvYXNjaWl0aWxkZSAxMjcvLm5vdGRlZiAxMzAvcXVvdGVzaW5nbGJhc2UvZmxvcmluL3F1b3RlZGJsYmFzZS9lbGxpcHNpcy9kYWdnZXIvZGFnZ2VyZGJsL2NpcmN1bWZsZXgvcGVydGhvdXNhbmQvU2Nhcm9uL2d1aWxzaW5nbGxlZnQvT0UgMTQxLy5ub3RkZWYgMTQ3L3F1b3RlZGJsbGVmdC9xdW90ZWRibHJpZ2h0L2J1bGxldC9lbmRhc2gvZW1kYXNoL3RpbGRlL3RyYWRlbWFyay9zY2Fyb24vZ3VpbHNpbmdscmlnaHQvb2UgMTU3Ly5ub3RkZWYgMTU5L1lkaWVyZXNpcyAxNjAvLm5vdGRlZiAxNjEvZXhjbGFtZG93bi9jZW50L3N0ZXJsaW5nL2N1cnJlbmN5L3llbi9icm9rZW5iYXIvc2VjdGlvbi9kaWVyZXNpcy9jb3B5cmlnaHQvb3JkZmVtaW5pbmUvZ3VpbGxlbW90bGVmdC9sb2dpY2Fsbm90L2h5cGhlbi9yZWdpc3RlcmVkL21hY3Jvbi9kZWdyZWUvcGx1c21pbnVzL3R3b3N1cGVyaW9yL3RocmVlc3VwZXJpb3IvYWN1dGUvbXUvcGFyYWdyYXBoL3BlcmlvZGNlbnRlcmVkL2NlZGlsbGEvb25lc3VwZXJpb3Ivb3JkbWFzY3VsaW5lL2d1aWxsZW1vdHJpZ2h0L29uZXF1YXJ0ZXIvb25laGFsZi90aHJlZXF1YXJ0ZXJzL3F1ZXN0aW9uZG93bi9BZ3JhdmUvQWFjdXRlL0FjaXJjdW1mbGV4L0F0aWxkZS9BZGllcmVzaXMvQXJpbmcvQUUvQ2NlZGlsbGEvRWdyYXZlL0VhY3V0ZS9FY2lyY3VtZmxleC9FZGllcmVzaXMvSWdyYXZlL0lhY3V0ZS9JY2lyY3VtZmxleC9JZGllcmVzaXMvRXRoL050aWxkZS9PZ3JhdmUvT2FjdXRlL09jaXJjdW1mbGV4L090aWxkZS9PZGllcmVzaXMvbXVsdGlwbHkvT3NsYXNoL1VncmF2ZS9VYWN1dGUvVWNpcmN1bWZsZXgvVWRpZXJlc2lzL1lhY3V0ZS9UaG9ybi9nZXJtYW5kYmxzL2FncmF2ZS9hYWN1dGUvYWNpcmN1bWZsZXgvYXRpbGRlL2FkaWVyZXNpcy9hcmluZy9hZS9jY2VkaWxsYS9lZ3JhdmUvZWFjdXRlL2VjaXJjdW1mbGV4L2VkaWVyZXNpcy9pZ3JhdmUvaWFjdXRlL2ljaXJjdW1mbGV4L2lkaWVyZXNpcy9ldGgvbnRpbGRlL29ncmF2ZS9vYWN1dGUvb2NpcmN1bWZsZXgvb3RpbGRlL29kaWVyZXNpcy9kaXZpZGUvb3NsYXNoL3VncmF2ZS91YWN1dGUvdWNpcmN1bWZsZXgvdWRpZXJlc2lzL3lhY3V0ZS90aG9ybi95ZGllcmVzaXNdCj4+IGVuZG9iago4MCAwIG9iaiA8PAovVHlwZSAvRm9udAovU3VidHlwZSAvVHlwZTEKL0VuY29kaW5nIDk0IDAgUgovQmFzZUZvbnQgL1RpbWVzLVJvbWFuCj4+IGVuZG9iago3MiAwIG9iaiA8PAovVHlwZSAvRm9udAovU3VidHlwZSAvVHlwZTEKL0VuY29kaW5nIDk0IDAgUgovQmFzZUZvbnQgL1RpbWVzLUl0YWxpYwo+PiBlbmRvYmoKNzEgMCBvYmogPDwKL1R5cGUgL0ZvbnQKL1N1YnR5cGUgL1R5cGUxCi9FbmNvZGluZyA5NCAwIFIKL0Jhc2VGb250IC9Db3VyaWVyCj4+IGVuZG9iago1OSAwIG9iaiA8PAovVHlwZSAvRm9udAovU3VidHlwZSAvVHlwZTEKL0VuY29kaW5nIDk0IDAgUgovQmFzZUZvbnQgL1RpbWVzLUJvbGQKPj4gZW5kb2JqCjU4IDAgb2JqIDw8Ci9UeXBlIC9Gb250Ci9TdWJ0eXBlIC9UeXBlMQovRW5jb2RpbmcgOTQgMCBSCi9CYXNlRm9udCAvQ291cmllci1PYmxpcXVlCj4+IGVuZG9iago1NyAwIG9iaiA8PAovVHlwZSAvRm9udAovU3VidHlwZSAvVHlwZTEKL0VuY29kaW5nIDk0IDAgUgovQmFzZUZvbnQgL1RpbWVzLVJvbWFuCj4+IGVuZG9iago1NiAwIG9iaiA8PAovVHlwZSAvRm9udAovU3VidHlwZSAvVHlwZTEKL0VuY29kaW5nIDk0IDAgUgovQmFzZUZvbnQgL0hlbHZldGljYQo+PiBlbmRvYmoKNzMgMCBvYmogPDwKL1R5cGUgL1BhZ2VzCi9Db3VudCAzCi9LaWRzIFs0OSAwIFIgNzYgMCBSIDg1IDAgUl0KPj4gZW5kb2JqCjk1IDAgb2JqIDw8Ci9UeXBlIC9PdXRsaW5lcwovRmlyc3QgNyAwIFIKL0xhc3QgNDcgMCBSCi9Db3VudCA1Cj4+IGVuZG9iago0NyAwIG9iaiA8PAovVGl0bGUgNDggMCBSCi9BIDQ2IDAgUgovUGFyZW50IDk1IDAgUgovUHJldiA0MyAwIFIKPj4gZW5kb2JqCjQzIDAgb2JqIDw8Ci9UaXRsZSA0NCAwIFIKL0EgNDIgMCBSCi9QYXJlbnQgOTUgMCBSCi9QcmV2IDE1IDAgUgovTmV4dCA0NyAwIFIKPj4gZW5kb2JqCjM5IDAgb2JqIDw8Ci9UaXRsZSA0MCAwIFIKL0EgMzggMCBSCi9QYXJlbnQgMTUgMCBSCi9QcmV2IDM1IDAgUgo+PiBlbmRvYmoKMzUgMCBvYmogPDwKL1RpdGxlIDM2IDAgUgovQSAzNCAwIFIKL1BhcmVudCAxNSAwIFIKL1ByZXYgMzEgMCBSCi9OZXh0IDM5IDAgUgo+PiBlbmRvYmoKMzEgMCBvYmogPDwKL1RpdGxlIDMyIDAgUgovQSAzMCAwIFIKL1BhcmVudCAxNSAwIFIKL1ByZXYgMjcgMCBSCi9OZXh0IDM1IDAgUgo+PiBlbmRvYmoKMjcgMCBvYmogPDwKL1RpdGxlIDI4IDAgUgovQSAyNiAwIFIKL1BhcmVudCAxNSAwIFIKL1ByZXYgMTkgMCBSCi9OZXh0IDMxIDAgUgo+PiBlbmRvYmoKMjMgMCBvYmogPDwKL1RpdGxlIDI0IDAgUgovQSAyMiAwIFIKL1BhcmVudCAxOSAwIFIKPj4gZW5kb2JqCjE5IDAgb2JqIDw8Ci9UaXRsZSAyMCAwIFIKL0EgMTggMCBSCi9QYXJlbnQgMTUgMCBSCi9OZXh0IDI3IDAgUgovRmlyc3QgMjMgMCBSCi9MYXN0IDIzIDAgUgovQ291bnQgLTEKPj4gZW5kb2JqCjE1IDAgb2JqIDw8Ci9UaXRsZSAxNiAwIFIKL0EgMTQgMCBSCi9QYXJlbnQgOTUgMCBSCi9QcmV2IDExIDAgUgovTmV4dCA0MyAwIFIKL0ZpcnN0IDE5IDAgUgovTGFzdCAzOSAwIFIKL0NvdW50IC01Cj4+IGVuZG9iagoxMSAwIG9iaiA8PAovVGl0bGUgMTIgMCBSCi9BIDEwIDAgUgovUGFyZW50IDk1IDAgUgovUHJldiA3IDAgUgovTmV4dCAxNSAwIFIKPj4gZW5kb2JqCjcgMCBvYmogPDwKL1RpdGxlIDggMCBSCi9BIDYgMCBSCi9QYXJlbnQgOTUgMCBSCi9OZXh0IDExIDAgUgo+PiBlbmRvYmoKOTYgMCBvYmogPDwKL05hbWVzIFsoRG9jLVN0YXJ0KSA1MSAwIFIgKEl0ZW0uMSkgODEgMCBSIChJdGVtLjIpIDgyIDAgUiAocGFnZS4xKSA1MiAwIFIgKHBhZ2UuMikgNzQgMCBSIChwYWdlLjMpIDgzIDAgUiAoc2VjdGlvbi4xKSA1IDAgUiAoc2VjdGlvbi4yKSA5IDAgUiAoc2VjdGlvbi4zKSAxMyAwIFIgKHNlY3Rpb24uNCkgNDEgMCBSIChzZWN0aW9uLjUpIDQ1IDAgUiAoc3Vic2VjdGlvbi4zLjEpIDE3IDAgUiAoc3Vic2VjdGlvbi4zLjIpIDI1IDAgUiAoc3Vic2VjdGlvbi4zLjMpIDI5IDAgUiAoc3Vic2VjdGlvbi4zLjQpIDMzIDAgUiAoc3Vic2VjdGlvbi4zLjUpIDM3IDAgUiAoc3Vic3Vic2VjdGlvbi4zLjEuMSkgMjEgMCBSXQovTGltaXRzIFsoRG9jLVN0YXJ0KSAoc3Vic3Vic2VjdGlvbi4zLjEuMSldCj4+IGVuZG9iago5NyAwIG9iaiA8PAovS2lkcyBbOTYgMCBSXQo+PiBlbmRvYmoKOTggMCBvYmogPDwKL0Rlc3RzIDk3IDAgUgo+PiBlbmRvYmoKOTkgMCBvYmogPDwKL1R5cGUgL0NhdGFsb2cKL1BhZ2VzIDczIDAgUgovT3V0bGluZXMgOTUgMCBSCi9OYW1lcyA5OCAwIFIKIC9QYWdlTW9kZSAvVXNlT3V0bGluZXMgL1VSSSA8PCAvQmFzZSAoKSA+PiAgL1ZpZXdlclByZWZlcmVuY2VzIDw8ID4+IAovT3BlbkFjdGlvbiA1MCAwIFIKPj4gZW5kb2JqCjEwMCAwIG9iaiA8PAogL0F1dGhvciAoKSAvVGl0bGUgKCkgL1N1YmplY3QgKCkgL0NyZWF0b3IgKExhVGVYIHdpdGggaHlwZXJyZWYgcGFja2FnZSkgL1Byb2R1Y2VyIChwZGZUZVgxMy5jKSAvS2V5d29yZHMgKCkgCi9DcmVhdG9yIChUZVgpCi9Qcm9kdWNlciAocGRmVGVYLTAuMTNjKQovQ3JlYXRpb25EYXRlIChEOjE5OTkxMDIzMDM0MjAwKQo+PiBlbmRvYmoKeHJlZgowIDEwMQowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDMwMDcgMDAwMDAgbiAKMDAwMDAwNDMyNSAwMDAwMCBuIAowMDAwMDA0NDEyIDAwMDAwIG4gCjAwMDAwMDQ1MTIgMDAwMDAgbiAKMDAwMDAwNjQwMSAwMDAwMCBuIAowMDAwMDAwMDA5IDAwMDAwIG4gCjAwMDAwMTgwODIgMDAwMDAgbiAKMDAwMDAwMDA1NCAwMDAwMCBuIAowMDAwMDA2NDU0IDAwMDAwIG4gCjAwMDAwMDAwODcgMDAwMDAgbiAKMDAwMDAxNzk5NiAwMDAwMCBuIAowMDAwMDAwMTMzIDAwMDAwIG4gCjAwMDAwMDk2NDEgMDAwMDAgbiAKMDAwMDAwMDE2MSAwMDAwMCBuIAowMDAwMDE3ODcyIDAwMDAwIG4gCjAwMDAwMDAyMDcgMDAwMDAgbiAKMDAwMDAwOTY5NSAwMDAwMCBuIAowMDAwMDAwMjQyIDAwMDAwIG4gCjAwMDAwMTc3NjEgMDAwMDAgbiAKMDAwMDAwMDI5MyAwMDAwMCBuIAowMDAwMDA5NzQ5IDAwMDAwIG4gCjAwMDAwMDAzMzcgMDAwMDAgbiAKMDAwMDAxNzcwMCAwMDAwMCBuIAowMDAwMDAwMzkzIDAwMDAwIG4gCjAwMDAwMDk4MDMgMDAwMDAgbiAKMDAwMDAwMDQ0MCAwMDAwMCBuIAowMDAwMDE3NjEzIDAwMDAwIG4gCjAwMDAwMDA0OTEgMDAwMDAgbiAKMDAwMDAwOTg1NyAwMDAwMCBuIAowMDAwMDAwNTI2IDAwMDAwIG4gCjAwMDAwMTc1MjYgMDAwMDAgbiAKMDAwMDAwMDU3NyAwMDAwMCBuIAowMDAwMDA5OTExIDAwMDAwIG4gCjAwMDAwMDA2MTcgMDAwMDAgbiAKMDAwMDAxNzQzOSAwMDAwMCBuIAowMDAwMDAwNjY4IDAwMDAwIG4gCjAwMDAwMDk5NjUgMDAwMDAgbiAKMDAwMDAwMDcwNCAwMDAwMCBuIAowMDAwMDE3MzY1IDAwMDAwIG4gCjAwMDAwMDA3NTUgMDAwMDAgbiAKMDAwMDAxMzAxMyAwMDAwMCBuIAowMDAwMDAwNzgyIDAwMDAwIG4gCjAwMDAwMTcyNzggMDAwMDAgbiAKMDAwMDAwMDgyOCAwMDAwMCBuIAowMDAwMDEzMDY3IDAwMDAwIG4gCjAwMDAwMDA4NjYgMDAwMDAgbiAKMDAwMDAxNzIwNCAwMDAwMCBuIAowMDAwMDAwOTEyIDAwMDAwIG4gCjAwMDAwMDI4MDQgMDAwMDAgbiAKMDAwMDAwMDk0OSAwMDAwMCBuIAowMDAwMDA2MzQ3IDAwMDAwIG4gCjAwMDAwMDYyOTMgMDAwMDAgbiAKMDAwMDAwNjUwNiAwMDAwMCBuIAowMDAwMDAwOTk5IDAwMDAwIG4gCjAwMDAwMDI3ODMgMDAwMDAgbiAKMDAwMDAxNjk3MCAwMDAwMCBuIAowMDAwMDE2ODgwIDAwMDAwIG4gCjAwMDAwMTY3ODYgMDAwMDAgbiAKMDAwMDAxNjY5NyAwMDAwMCBuIAowMDAwMDA0NjM3IDAwMDAwIG4gCjAwMDAwMDQ3ODIgMDAwMDAgbiAKMDAwMDAwNDkyNiAwMDAwMCBuIAowMDAwMDA1MDcyIDAwMDAwIG4gCjAwMDAwMDUyMjYgMDAwMDAgbiAKMDAwMDAwNTM4NiAwMDAwMCBuIAowMDAwMDA1NTQwIDAwMDAwIG4gCjAwMDAwMDU2OTQgMDAwMDAgbiAKMDAwMDAwNTg0OCAwMDAwMCBuIAowMDAwMDA2MDAxIDAwMDAwIG4gCjAwMDAwMDYxNDcgMDAwMDAgbiAKMDAwMDAxNjYxMSAwMDAwMCBuIAowMDAwMDE2NTIwIDAwMDAwIG4gCjAwMDAwMTcwNTggMDAwMDAgbiAKMDAwMDAwOTU4NyAwMDAwMCBuIAowMDAwMDEwMDE5IDAwMDAwIG4gCjAwMDAwMDkyOTkgMDAwMDAgbiAKMDAwMDAwNjY3MiAwMDAwMCBuIAowMDAwMDA5Mjc4IDAwMDAwIG4gCjAwMDAwMDk0MzIgMDAwMDAgbiAKMDAwMDAxNjQzMCAwMDAwMCBuIAowMDAwMDEyOTA1IDAwMDAwIG4gCjAwMDAwMTI5NTkgMDAwMDAgbiAKMDAwMDAxMjg1MSAwMDAwMCBuIAowMDAwMDEzMTIxIDAwMDAwIG4gCjAwMDAwMTI3MzcgMDAwMDAgbiAKMDAwMDAxMDE4NSAwMDAwMCBuIAowMDAwMDEyNzE2IDAwMDAwIG4gCjAwMDAwMTM0OTggMDAwMDAgbiAKMDAwMDAxMzI2MyAwMDAwMCBuIAowMDAwMDEzNDc4IDAwMDAwIG4gCjAwMDAwMTM3NDMgMDAwMDAgbiAKMDAwMDAxNDAyMCAwMDAwMCBuIAowMDAwMDE0NjA4IDAwMDAwIG4gCjAwMDAwMTQ2NDIgMDAwMDAgbiAKMDAwMDAxNzEzMSAwMDAwMCBuIAowMDAwMDE4MTUzIDAwMDAwIG4gCjAwMDAwMTg1NjkgMDAwMDAgbiAKMDAwMDAxODYwNiAwMDAwMCBuIAowMDAwMDE4NjQyIDAwMDAwIG4gCjAwMDAwMTg4MTQgMDAwMDAgbiAKdHJhaWxlcgo8PAovU2l6ZSAxMDEKL1Jvb3QgOTkgMCBSCi9JbmZvIDEwMCAwIFIKPj4Kc3RhcnR4cmVmCjE5MDIwCiUlRU9GCg==");
		} catch (Exception e) {
		LOG.error("Error al ejecutar query " + e.getMessage());
		e.printStackTrace();
		}
		return pdf;
	}
		
	@RequestMapping(value = "/recibirPDF", method = RequestMethod.POST)
		public long recibirPDF(InputStream is) throws IOException {
		
		DocumentoDigital documento = new DocumentoDigital();
		long id = docDigiService.crearDocumentoDigital(documento);

		ByteArrayOutputStream buffer = new ByteArrayOutputStream();
		
		int nRead;
		byte[] data = new byte[16384];
		
		while ((nRead = is.read(data, 0, data.length)) != -1) {
			  buffer.write(data, 0, nRead);
			}
		
		buffer.toByteArray();
		
		documento.setBase64(Base64.getEncoder().encodeToString(buffer.toByteArray()));
		 
		return id;
		
		 
	}
}
